### ISSUE TITLE
User endpoint needs to be created

### ISSUE THREAD

**Issue by IanWorley** [X-Men-SE-CB-Fall-2023/CB-Project#11]
#### Tasks:
 

- [x] Create a url endpoint that accpets the required fields in a JSON Body of Username: String, Password: String, Roles: List[String]
- [x] Hash the password in the database **(I know Frank tells you this is hard but it is not trust me. I will help if need ~ @IanWorley )**
- [x] Create the user using Spring Security 
- [x] Save the User into the database using Spring JPA
- [x] Attempt to login as user using spring session **(If this needs to be move to sprint 2 or split as another issue please inform me asap)**
