### ISSUE TITLE
Add user endpoint that displays username and general user info

### ISSUE THREAD

**Issue by IanWorley** [X-Men-SE-CB-Fall-2023/CB-Project#12]
## Issue Description
As to knowledge of spring there is not any good automatic way of grabbing user information without having a custom endpoint. I suggest that the api endpoint should be: /api/v1/user/me which should return json data of the user that is login

## Tasks

- [x] Create a protected url endpoint named: /api/v1/user/me
- [ ] Make the data return user data of: username , roles, and other data besides password 
- [ ] Write test to prove that is url endpoint works
- [ ] Document this in Open API

**Comment by IanWorley** [comment]
This one is tricky if you have any questions do not hesitate to reach out @KyleFaris
