### ISSUE TITLE
Add User endpoints that allow from CRUD actions

### ISSUE THREAD

**Issue by IanWorley** [X-Men-SE-CB-Fall-2023/CB-Project#14]
### Issue Description
Add endpoints for create, update, read  and delete for user using the path /api/v1/user

#### Tasks

- [x] Create user endpoint with post /api/v1/user 
- [x] Delete user endpoint with delete /api/v1/user?id=number
- [x] Update user endpoint with put /api/v1/user?id=number
- [x] Read user endpoint with get /api/v1/user?id=number
