### ISSUE TITLE
Create a away for the user to submit user credentials

### ISSUE THREAD

**Issue by IanWorley** [X-Men-SE-CB-Fall-2023/CB-Project#8]
### Issue Description
In this issue, we will create the necessary components for the user credentials submission form. What is required is the basic html,
css structure, react components 

### Task

- [x]  Create field to fill out username
- [x] Create field to fill out password 
- [x] Create button to submit user credentials **(This does not require a connection to the backend)**
- [x] Create response design for desktop users
- [ ] Document the components the login components

**Comment by IanWorley** [comment]
[Figma design ](https://www.figma.com/proto/QoeXN2FtKyzmbUgcINgyiU/Commerce-Bank-Prototype?node-id=1-2&starting-point-node-id=1%3A2 ) @KyleFaris
